import * as React from 'react'
import { Download, FileText, Check } from 'lucide-react'
import { useTranslation } from 'react-i18next'
import { Button } from '@/components/ui/button'
import { useToast } from '@/components/ui/toast'
import { cn } from '@/lib/utils'

interface ExportButtonProps {
  format: 'pdf' | 'docx'
  documentTitle: string
  onExportDone?: () => void
}

type ExportStep = 'idle' | 'reading' | 'rendering' | 'generating' | 'done' | 'error'

const STEP_KEYS: Record<ExportStep, string> = {
  idle: '',
  reading: 'builder.exportStepReading',
  rendering: 'builder.exportStepRendering',
  generating: 'builder.exportStepGenerating',
  done: 'builder.exportStepReady',
  error: 'builder.exportError',
}

const STEP_ORDER: ExportStep[] = ['reading', 'rendering', 'generating', 'done']

function ProgressSteps({ current }: { current: ExportStep }) {
  const { t } = useTranslation()
  const steps = STEP_ORDER.slice(0, 3) // reading, rendering, generating

  return (
    <div className="flex flex-col gap-1.5 w-full mt-2">
      {steps.map((step) => {
        const idx = STEP_ORDER.indexOf(step)
        const currentIdx = STEP_ORDER.indexOf(current)
        const isDone = currentIdx > idx
        const isActive = step === current

        return (
          <div key={step} className={cn('flex items-center gap-2 text-xs', isDone ? 'text-ds-success-foreground' : isActive ? 'text-foreground' : 'text-muted-foreground/40')}>
            <div className={cn('size-4 rounded-full flex items-center justify-center shrink-0 border',
              isDone ? 'bg-ds-success border-ds-success text-ds-success-foreground' :
              isActive ? 'border-primary bg-primary/10' :
              'border-muted',
            )}>
              {isDone
                ? <Check className="size-2.5" strokeWidth={3} />
                : isActive
                ? <div className="size-1.5 rounded-full bg-primary animate-pulse" />
                : null}
            </div>
            <span>{t(STEP_KEYS[step])}</span>
          </div>
        )
      })}
    </div>
  )
}

export function ExportButton({ format, documentTitle, onExportDone }: ExportButtonProps) {
  const { t } = useTranslation()
  const { toast } = useToast()
  const [exportStep, setExportStep] = React.useState<ExportStep>('idle')

  const isLoading = exportStep !== 'idle' && exportStep !== 'done' && exportStep !== 'error'

  const handleExport = async () => {
    setExportStep('reading')
    try {
      await new Promise((res) => setTimeout(res, 500))
      setExportStep('rendering')
      await new Promise((res) => setTimeout(res, 600))
      setExportStep('generating')
      await new Promise((res) => setTimeout(res, 700))

      if (format === 'pdf') {
        // Clone the template HTML into a direct <body> child so nested
        // overflow:hidden containers cannot clip it during printing.
        const templateEl = document.querySelector('.preview-page-wrap')
        const printRoot = document.createElement('div')
        printRoot.id = 'ds-print-root'
        if (templateEl) {
          printRoot.innerHTML = templateEl.innerHTML
        }
        document.body.appendChild(printRoot)

        const style = document.createElement('style')
        style.id = 'ds-print-style'
        style.textContent = `
          @media print {
            html, body {
              margin: 0 !important;
              padding: 0 !important;
              width: 794px !important;
            }
            body > *:not(#ds-print-root) { display: none !important; }
            #ds-print-root {
              display: block !important;
              position: static !important;
              width: 794px !important;
              margin: 0 !important;
              padding: 0 !important;
              overflow: visible !important;
              background: white !important;
            }
            @page { margin: 0; size: A4; }
          }
        `
        document.head.appendChild(style)
        window.print()
        document.head.removeChild(style)
        document.body.removeChild(printRoot)
      } else {
        const content = `${documentTitle}\n\nGenerated by DocuSmart\n\nThis document was created with DocuSmart.\nVisit docusmart.app to create your own.\n`
        const blob = new Blob([content], {
          type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        })
        const url = URL.createObjectURL(blob)
        const a = document.createElement('a')
        a.href = url
        a.download = `${documentTitle.replace(/[^a-zA-Z0-9\s]/g, '').trim().replace(/\s+/g, '_')}.docx`
        document.body.appendChild(a)
        a.click()
        document.body.removeChild(a)
        URL.revokeObjectURL(url)
      }

      setExportStep('done')
      toast(t('builder.exportSuccess'), 'success')
      onExportDone?.()
      setTimeout(() => setExportStep('idle'), 2000)
    } catch {
      setExportStep('error')
      toast(t('builder.exportError'), 'error')
      setTimeout(() => setExportStep('idle'), 2000)
    }
  }

  if (format === 'pdf') {
    return (
      <div className="flex flex-col">
        <Button
          onClick={handleExport}
          disabled={isLoading}
          className="w-full h-12 text-base gap-2"
          size="lg"
        >
          {exportStep === 'done'
            ? <><Check className="size-4" />{t('builder.exportStepReady')}</>
            : <><Download className="size-4" />{isLoading ? t(STEP_KEYS[exportStep]) : t('builder.downloadPDF')}</>
          }
        </Button>
        {isLoading && <ProgressSteps current={exportStep} />}
      </div>
    )
  }

  return (
    <div className="flex flex-col">
      <Button
        variant="outline"
        onClick={handleExport}
        disabled={isLoading}
        className="w-full gap-2"
      >
        {exportStep === 'done'
          ? <><Check className="size-4" />{t('builder.exportStepReady')}</>
          : <><FileText className="size-4" />{isLoading ? t(STEP_KEYS[exportStep]) : t('builder.downloadDOCX')}</>
        }
      </Button>
      {isLoading && <ProgressSteps current={exportStep} />}
    </div>
  )
}
